// Generated by extract_green.py from Green database
// Descriptions of available data files
provides_knot_data("green_0-4.js", 'green', [1], [0,1,2,3,4], ["crossing_number","components","alexander","arrow1","arrow2"]);
provides_knot_data("green_5.js", 'green', [1], [5], ["crossing_number","components","alexander","arrow1","arrow2"]);
provides_knot_data("green_0-4_extra.js", 'green', [1], [0,1,2,3,4], ["arrow3"]);
provides_knot_data("green_5_extra.js", 'green', [1], [5], ["arrow3"]);
