// Generated by extract_knotinfo.py from KnotInfo database
// Descriptions of available data files
provides_knot_data("knotinfo_0-10.js", [1], [0,1,2,3,4,5,6,7,8,9,10], ["crossing_number","components","katlas","genus","signature","conway","jones","turaev_genus","bridge_number"]);
provides_knot_data("knotinfo_11-12.js", [1], [11,12], ["crossing_number","components","katlas","genus","signature","conway","jones","turaev_genus","bridge_number"]);
provides_knot_data("knotinfo_0-10_pd.js", [1], [0,1,2,3,4,5,6,7,8,9,10], ["pd"]);
provides_knot_data("knotinfo_11-12_pd.js", [1], [11,12], ["pd"]);
provides_knot_data("linkinfo_0-10.js", [2,3,4,5], [0,1,2,3,4,5,6,7,8,9,10], ["crossing_number","components","katlas","signature","conway","jones"]);
provides_knot_data("linkinfo_11.js", [2,3,4,5], [11], ["crossing_number","components","katlas","signature","conway","jones"]);
provides_knot_data("linkinfo_0-10_pd.js", [2,3,4,5], [0,1,2,3,4,5,6,7,8,9,10], ["pd"]);
provides_knot_data("linkinfo_11_pd.js", [2,3,4,5], [11], ["pd"]);
